services:
  postgres:
    image: postgres:16
    container_name: medflow-postgres
    environment:
      POSTGRES_USER: medflow
      POSTGRES_PASSWORD: medflow_pass
      POSTGRES_DB: medflow_db
    ports:
      - "5432:5432"
    volumes:
      - medflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medflow -d medflow_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  medflow_pgdata: