"""add triage sessions table

Revision ID: e404faaca23e
Revises: d2a670a6a94b
Create Date: 2026-03-09 03:50:13.112417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e404faaca23e'
down_revision: Union[str, None] = 'd2a670a6a94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('initial_case', sa.Text(), nullable=False),
    sa.Column('qa_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latest_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('missing_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_sessions_encounter_id'), 'triage_sessions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_triage_sessions_patient_id'), 'triage_sessions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_sessions_patient_id'), table_name='triage_sessions')
    op.drop_index(op.f('ix_triage_sessions_encounter_id'), table_name='triage_sessions')
    op.drop_table('triage_sessions')
    # ### end Alembic commands ###
